
package rgcrawlerservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrawlerServerService", targetNamespace = "http://rgcrawlerws/", wsdlLocation = "http://localhost:9876/crawler?wsdl")
public class CrawlerServerService
    extends Service
{

    private final static URL CRAWLERSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRAWLERSERVERSERVICE_EXCEPTION;
    private final static QName CRAWLERSERVERSERVICE_QNAME = new QName("http://rgcrawlerws/", "CrawlerServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/crawler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRAWLERSERVERSERVICE_WSDL_LOCATION = url;
        CRAWLERSERVERSERVICE_EXCEPTION = e;
    }

    public CrawlerServerService() {
        super(__getWsdlLocation(), CRAWLERSERVERSERVICE_QNAME);
    }

    public CrawlerServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRAWLERSERVERSERVICE_QNAME, features);
    }

    public CrawlerServerService(URL wsdlLocation) {
        super(wsdlLocation, CRAWLERSERVERSERVICE_QNAME);
    }

    public CrawlerServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRAWLERSERVERSERVICE_QNAME, features);
    }

    public CrawlerServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrawlerServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICrawlerServer
     */
    @WebEndpoint(name = "CrawlerServerPort")
    public ICrawlerServer getCrawlerServerPort() {
        return super.getPort(new QName("http://rgcrawlerws/", "CrawlerServerPort"), ICrawlerServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICrawlerServer
     */
    @WebEndpoint(name = "CrawlerServerPort")
    public ICrawlerServer getCrawlerServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rgcrawlerws/", "CrawlerServerPort"), ICrawlerServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRAWLERSERVERSERVICE_EXCEPTION!= null) {
            throw CRAWLERSERVERSERVICE_EXCEPTION;
        }
        return CRAWLERSERVERSERVICE_WSDL_LOCATION;
    }

}
