
package rgcrawlerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICrawlerServer", targetNamespace = "http://rgcrawlerws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICrawlerServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://rgcrawlerws/ICrawlerServer/getFeedJsonRequest", output = "http://rgcrawlerws/ICrawlerServer/getFeedJsonResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://rgcrawlerws/ICrawlerServer/getFeedJson/Fault/Exception")
    })
    public String getFeedJson(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://rgcrawlerws/ICrawlerServer/getFeedJsonLocalRequest", output = "http://rgcrawlerws/ICrawlerServer/getFeedJsonLocalResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://rgcrawlerws/ICrawlerServer/getFeedJsonLocal/Fault/Exception")
    })
    public String getFeedJsonLocal(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

}
